allowBuilds:
  '@swc/core': true
  esbuild: true
  sharp: true
minimumReleaseAgeExclude:
  - '@tanstack/eslint-plugin-query@5.101.2'
  - '@tanstack/query-async-storage-persister@5.101.2'
  - '@tanstack/query-core@5.101.2'
  - '@tanstack/query-devtools@5.101.2'
  - '@tanstack/query-persist-client-core@5.101.2'
  - '@tanstack/react-query-devtools@5.101.2'
  - '@tanstack/react-query-persist-client@5.101.2'
  - '@tanstack/react-query@5.101.2'
  - daisyui@5.6.10 || 5.6.16
  - '@types/node@26.1.1'
  - '@typescript/typescript-aix-ppc64@7.0.2'
  - '@typescript/typescript-darwin-arm64@7.0.2'
  - '@typescript/typescript-darwin-x64@7.0.2'
  - '@typescript/typescript-freebsd-arm64@7.0.2'
  - '@typescript/typescript-freebsd-x64@7.0.2'
  - '@typescript/typescript-linux-arm64@7.0.2'
  - '@typescript/typescript-linux-arm@7.0.2'
  - '@typescript/typescript-linux-loong64@7.0.2'
  - '@typescript/typescript-linux-mips64el@7.0.2'
  - '@typescript/typescript-linux-ppc64@7.0.2'
  - '@typescript/typescript-linux-riscv64@7.0.2'
  - '@typescript/typescript-linux-s390x@7.0.2'
  - '@typescript/typescript-linux-x64@7.0.2'
  - '@typescript/typescript-netbsd-arm64@7.0.2'
  - '@typescript/typescript-netbsd-x64@7.0.2'
  - '@typescript/typescript-openbsd-arm64@7.0.2'
  - '@typescript/typescript-openbsd-x64@7.0.2'
  - '@typescript/typescript-sunos-x64@7.0.2'
  - '@typescript/typescript-win32-arm64@7.0.2'
  - '@typescript/typescript-win32-x64@7.0.2'
  - typescript@7.0.2
onlyBuiltDependencies:
  - '@swc/core'
  - esbuild
  - sharp
